import type { NextPage } from 'next'
import Head from 'next/head'
import Button, { NestedBtn, SVG } from '../components/Button'
import { H1, H2, H3, P } from '../components/Common/Typography'
import PreviewDescription, { Divider } from '../components/PreviewDescription'
import { Row, Column } from '../components/Common/FlexBox'
import PreviewImage from '../components/PreviewImage'
import styled from 'styled-components'
import Navbar from '../components/Navbar/Navbar'
import Hero from '../components/Hero/Hero'
import Footer from '../components/Common/Footer'
import MainPage from './main'
import { fetchHomePageContent } from '../contentfulPosts'
import ProjectPage from './project'
export const Container = styled.section`

`
export const Main = styled.div`
  width: 80%;
  max-width: 1440px;
  margin: auto;
`
interface HomePageProps {
  portfolioPictureURL: string,
  tagLine: string,
  aboutMe: string,
  CTA: string,

  // onclick: ()=>void;

}
const Home: NextPage<HomePageProps> = (props) => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero src={props.portfolioPictureURL} />
      <Main>
        <Row>
          <Column>
            <PreviewImage
              // srcSet= 
              sizes="(max-width: 600px) 480px,
              800px"
              src="/images/homepage/desktop/Facetune_07-05-2022-19-17-56.jpg"
              alt=""
            />
          </Column>
          <Column>
            <PreviewDescription
              title="About Me"
              description={props.aboutMe}
              onclick={() => alert("func works")}
            />
          </Column>
        </Row>

        <Row>
          <H2>Interested in doing a project together?</H2>
          <Divider />
          <Button variant="secondary"> Contact me</Button>
        </Row>
      </Main>
      {/* <ProjectPage
        sizes={props.sizes}
        src={props.src}
        alt={props.alt}
        title={props.title}
        description={props.description}
        onclick={() => console.log("clicked")}
      /> */}
      <Footer />
    </Container>

  )
}

export default Home
export async function getStaticProps() {
  const homePageProps: HomePageProps = await fetchHomePageContent()
  return {
    props: {
      ...homePageProps,
    },
  }
}
