import type { NextPage } from 'next'
import Head from 'next/head'
import Button, { NestedBtn, SVG } from '../components/Button'
import { H1, H2, H3, P } from '../components/Common/Typography'
import PreviewDescription, { Divider } from '../components/PreviewDescription'
import ProductCard from '../components/ProductCard'
import { Row, Column } from '../components/Common/FlexBox'
import styles from '../styles/Home.module.css'
import PreviewImage from '../components/PreviewImage'
import styled from 'styled-components'
import Navbar from '../components/Navbar/Navbar'
import Hero from '../components/Hero/Hero'
import Footer from '../components/Common/Footer'

export const Container = styled.section`

`
export const Main = styled.div`
  width: 80%;
  margin: auto;
`

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero src='/images/homepage/desktop/image-homepage-hero@2x.jpg' />
      <Main>
        <Row>
          <Column>
            <PreviewImage
              // srcSet= 
              sizes="(max-width: 600px) 480px,
            800px"
              src="/images/homepage/desktop/image-homepage-profile@2x.jpg"
              alt=""
            />
          </Column>
          <Column>
            <PreviewDescription
              title="About Me"
              description="I’m a junior front-end developer looking for a new role in an exciting company. I focus on writing accessible HTML, using modern CSS practices and writing clean JavaScript. When writing JavaScript code, I mostly use React, but I can adapt to whatever tools are required. I’m based in London, UK, but I’m happy working remotely and have experience in remote teams. When I’m not coding, you’ll find me outdoors. I love being out in nature whether that’s going for a walk, run or cycling. I’d love you to check out my work."
              onclick={() => alert("func works")}
            />
          </Column>
        </Row>
        <Row>
          <H2>Interested in doing <br />a project together?</H2>
          <Divider />
          <Button variant="secondary"> Contact me</Button>
        </Row>
      </Main>

      <Footer />
    </Container>

  )
}

export default Home
